[package]
name = "tandem-core"
version.workspace = true
edition.workspace = true

[dependencies]
ammonia = "4"
base64 = "0.22"
dirs = "6"
fastnbt = "2"
flate2 = "1"
futures-util = "0.3"
keyring = { version = "3", default-features = false, features = ["windows-native", "apple-native"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
md5 = "0.7"
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream", "http2"] }
serde.workspace = true
serde_json.workspace = true
sha1_smol = "1"
sha2 = "0.10"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite", "migrate", "macros"] }
sysinfo = { version = "0.39", default-features = false, features = ["system"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4"] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects"] }

[dev-dependencies]
tempfile = "3"
